name: Run Tado-Octopus Script

on:
  workflow_dispatch:
  schedule:
    # Runs every Wednesday at 12pm UTC
    - cron: '0 12 * * 3'

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Initialise playwright
      run: |
        playwright install

    - name: Run Python script
      run: |
        python sync_octopus_tado.py \
          --tado-email "${{ secrets.TADO_EMAIL }}" \
          --tado-password "${{ secrets.TADO_PASSWORD }}" \
          --mprn "${{ secrets.OCTOPUS_MPRN }}" \
          --gas-serial-number "${{ secrets.OCTOPUS_GAS_SERIAL }}" \
          --octopus-api-key "${{ secrets.OCTOPUS_API_KEY }}"
